In [13]:
import pandas as pd

In [14]:
data = pd.read_csv('color_data.csv')

In [15]:
data

         Color_Name Color_Family    R    G    B
0         indianred          Red  205   92   92
1        lightcoral          Red  240  128  128
2            salmon          Red  250  128  114
3        darksalmon          Red  233  150  122
4       lightsalmon         Pink  255  160  122
..              ...          ...  ...  ...  ...
134       lightgrey         Gray  211  211  211
135   darkslategrey         Gray   47   79   79
136  lightslategrey         Gray  119  136  153
137       slategrey         Gray  112  128  144
138           black        Black    0    0    0

[139 rows x 5 columns]

In [16]:
data = data.drop('Color_Name',axis = 1)

In [17]:
data

    Color_Family    R    G    B
0            Red  205   92   92
1            Red  240  128  128
2            Red  250  128  114
3            Red  233  150  122
4           Pink  255  160  122
..           ...  ...  ...  ...
134         Gray  211  211  211
135         Gray   47   79   79
136         Gray  119  136  153
137         Gray  112  128  144
138        Black    0    0    0

[139 rows x 4 columns]

In [18]:
colors = data['Color_Family'].tolist()
colors = list(dict.fromkeys(colors))
print(colors)

['Red', 'Pink', 'Orange', 'Yellow', 'Purple', 'Green', 'Blue', 'Brown', 'White', 'Gray', 'Black']

In [19]:
type(data)

pandas.core.frame.DataFrame

In [24]:
color_modify = []
for i in colors:
    R = 0
    G = 0
    B = 0
    C = 0
    for j in data.itertuples():
        if i == j.Color_Family:
           R = R + j.R
           G = G + j.G
           B = B + j.B
           C = C + 1
    color_modify.append([i,R/C,G/C,B/C])

In [25]:
color_modify

[['Red', 215.0, 69.0, 68.75],
 ['Pink', 241.85714285714286, 113.14285714285714, 160.71428571428572],
 ['Orange', 255.0, 120.0, 30.2],
 ['Yellow', 245.63636363636363, 232.27272727272728, 148.63636363636363],
 ['Purple', 165.78947368421052, 74.6842105263158, 202.73684210526315],
 ['Green', 72.21739130434783, 187.8695652173913, 77.82608695652173],
 ['Blue', 76.75, 160.29166666666666, 214.75],
 ['Brown', 208.11764705882354, 150.35294117647058, 101.70588235294117],
 ['White', 249.47058823529412, 246.7058823529412, 240.47058823529412],
 ['Gray', 127.28571428571429, 136.57142857142858, 141.28571428571428],
 ['Black', 0.0, 0.0, 0.0]]

In [26]:
df = pd.DataFrame(color_modify,columns = ['Color','R','G','B'])

In [27]:
df

     Color           R           G           B
0      Red  215.000000   69.000000   68.750000
1     Pink  241.857143  113.142857  160.714286
2   Orange  255.000000  120.000000   30.200000
3   Yellow  245.636364  232.272727  148.636364
4   Purple  165.789474   74.684211  202.736842
5    Green   72.217391  187.869565   77.826087
6     Blue   76.750000  160.291667  214.750000
7    Brown  208.117647  150.352941  101.705882
8    White  249.470588  246.705882  240.470588
9     Gray  127.285714  136.571429  141.285714
10   Black    0.000000    0.000000    0.000000

In [28]:
df.to_csv('color_dataset.csv',index=False)